### PR TITLE
Adding logos from the Radio Nav so the Nav can use this library

### PR DESCRIPTION
**Pull request by hammol04**
Adding various logos that the iPlayer Radio nav uses so this library can be integrated with the navigation.

Thank you,

@stephencoe , @Jayflux, @haslaa01 , @pris54 , @jijo78 , @steveculverwell

### CODE REVIEW

**Comment by steveculverwell** [comment]
was the centering issue narrowed down to the css or svg?

I'll raise it but they've been around for so long i guess it's expected...
The national graphics (coloured and uncoloured) are aligned differently. For coloured the text is padded to the left but for the transparents they are aligned to the edge. 

https://github.com/bbc/rmp-shared-assets/blob/master/assets/img/networks/bbc_london.svg
https://github.com/bbc/rmp-shared-assets/blob/master/assets/img/networks/bbc_london_colour.svg

**Comment by haslaa01** [comment]
I think that behaviour is expected, @steveculverwell as I think the logos tend to be used within different contexts.

Fundamentally, I think that the white logo is always supposed to be aligned to the left, whilst the coloured logo is supposed to have padding (as shown below).

#### White logo
white-logo

#### Coloured logo
coloured-logo

However, I do not think the logos included within this PR are the same as the ones to which you are referring, as I believe it only includes the logos used within the navigation bar.

As such, assuming the logos have simply been copied from the [`radio-nav-service` repository](https://github.com/bbc/radio-nav-service) to this one, I see no reason that this PR should not be merged.

:dancer:

**Comment by hammol04** [comment]
Thanks for the comments.

I've also had a brief discussion with @stephencoe about this about convention for stations with the same logo.

Do you agree that a suffix is good enough? e.g. bbc_radio_one_1.svg, bbc_radio_one_2.svg for variants to keep it clean.

**Comment by hammol04** [comment]
After discussion, we've decided to change the convention into putting the logos in a new folder so there can be easy looping rather than having to decide whether to use _1.svg or not, so there might be a couple of logo's that are the same however in the case of the Radio Nav, this is quite rare.

Squashed the commit from before.

**Comment by haslaa01** [comment]
I don't think it is necessarily important, but does anyone think it would be worth naming the folders based on the version of the logos contained within them?

I would be interested to hear your thoughts on the matter, @hammol04, @stephencoe or @Jayflux.

If everyone is happy to use numbers (as is currently the case), I see no reason that this PR should not be merged.

💃

**Comment by Jayflux** [comment]
How do you mean @haslaa01?
Could you give us an example?

**Comment by hammol04** [comment]
Like /radionav/bbc_radio_one.svg I think he means.

It's a good idea, but I just thought what if these assets ultimately won't end up being exclusive to the nav

**Comment by haslaa01** [comment]
@Jayflux, although @hammol04 has made a valid suggestion, I didn't necessarily mean something like `radionav` because, as he indicated, there would be less reason for them to reside within this repository if they were exclusive to a specific component.

As such, although I can't necessarily think of entirely appropriate names myself, I thought names that were representative of the differences between the logos might be a good way to distinguish them.

For example, the logos within this pull request are less complex than the others (in the sense that certain elements are removed from them) and, as such, they could be referred to as `simple`, `simplified`, `basic`, `refined` or something similar.

As I said, I do not necessarily think they are the most suitable suggestions, but I hope that they communicate my proposal a little better.

**Comment by hammol04** [comment]
Good idea, something like circular/bbc_radio_four.svg, I think as that is what make them unique.

**Comment by haslaa01** [comment]
@hammol04 - although there are evidently logos that will reside in other folders that will also be circular (which might lead to confusion), I would not take issue with that name if it was the name of preference to the other members of the team (e.g. @Jayflux and @stephencoe).

💃

**Comment by hammol04** [comment]
Done 🔵

**Comment by stephencoe** [comment]
We have to be careful with files that have duplicate names as the way this was originally intended was to copy the logos over in a flat directory

https://github.com/bbc/rmp-radio-nhp-service/blob/feature/shared-assets/Gruntfile.js#L180

Doing it this way would cause logos to overwrite each other. Maybe we need to discuss if there is a better way for the logos to be pulled in to avoid this

Also there are duplicate logos - i.e networks/circular/local_colour.svg & networks/local_colour.svg

**Comment by stephencoe** [comment]
Do you think its worth checking with UX whether the color logos should be inline with each other? If they agree then these could all use the same logos for the color versions

6music
https://github.com/bbc/rmp-shared-assets/blob/feature/radio-nav-logos/assets/img/networks/circular/bbc_6music_colour.svg

https://github.com/bbc/rmp-shared-assets/blob/feature/radio-nav-logos/assets/img/networks/bbc_6music_colour.svg

Asian network
https://github.com/bbc/rmp-shared-assets/blob/feature/radio-nav-logos/assets/img/networks/circular/bbc_asian_network_colour.svg

https://github.com/bbc/rmp-shared-assets/blob/feature/radio-nav-logos/assets/img/networks/bbc_asian_network_colour.svg

**Comment by hammol04** [comment]
I have removed the circular folder and named the logos _1 to show that they are part of the same group, to resolve the flatten: true issue.

I can raise it with UX about the differences in logos!

**Comment by hammol04** [comment]
Hello,

I have now updated this to meet the new folder and 'sid' naming requirements.

Thanks

@stephencoe @haslaa01 @jijo78 @Jayflux

**Comment by haslaa01** [comment]
Based on the assumption that everyone is happy with the new naming convention, I would be happy for this PR to be merged

💃

**Comment by stephencoe** [comment]
🍨

**Pull request merged**
