### PR TITLE
Removed unnecessary `bbc_radio_wales` logo that isn't named using sid

### PR DESCRIPTION
**Pull request by haslaa01**
The change within this PR removes the `bbc_radio_wales.svg` logo that @hammol04 noticed was unintentionally left within the `network-logos` directory.

@stephencoe - can you confirm that it would be safe to remove this logo?

### CODE REVIEW

**Comment by hammol04** [comment]
:shipit:

**Comment by stephencoe** [comment]
Looking at the network tab on http://www.bbc.co.uk/radiowales I would say not, unless you are going to use a different on in the nav now?

**Comment by haslaa01** [comment]
Well spotted, @stephencoe - following the discussion with @hammol04, I believe that the updated radionav will not use this logo.

**Comment by Jayflux** [comment]
I suppose this is dependant on https://github.com/bbc/rmp-radio-nhp-service/pull/218 being sorted

**Comment by stephencoe** [comment]
:shipit:

**Pull request merged**
