### PR TITLE
ipr 3124 Fix branding for jazz

### PR DESCRIPTION
**Pull request by steveculverwell**
https://jira.dev.bbc.co.uk/browse/IPR-3124

### CODE REVIEW

**Comment by alexgisby** [comment]
Lookin sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by alexgisby** [comment]
:shipit: looking sharp!

**Comment by stephencoe** [comment]
well it looks like @alexgisby thinks its looking sharp. 👍 from me

**Pull request closed without merging**
