### PR TITLE
Adding alternative local station icons

### PR DESCRIPTION
**Pull request by hammol04**
Hello

@haslaa01 @jijo78 @Jayflux @stephencoe @steveculverwell @pris54 

- I am adding alternative local stations required for the radio nav (schedules dropdown)
- I have run grunt (which has SVGO) and this has compressed the other images, further.

Thank you,
Laurence

### CODE REVIEW

**Comment by hammol04** [comment]
Investigation under way for some excessively sized local icons ...

**Comment by jijo78** [comment]
🇮🇹

**Comment by hammol04** [comment]
Fixed issue where we had very large local station images.

**Comment by haslaa01** [comment]
Good work, man 💃

**Pull request merged**
