### PR TITLE
Add safety net to prevent brittle code.

### PR DESCRIPTION
**Pull request by djmarland**
Composer file might not be found if a server is running on a specific file (such as to render feeds)

### CODE REVIEW

**Comment by BPScott** [comment]
'../composer.lock' shall be relative to the PHP file that is called (that then includes this file) which seems very brittle

**Comment by djmarland** [comment]
Indeed, hence adding this safety check. Ideally it would make better use of  `__DIR__` or another method. But I don't want to go breaking backwards compatibility. The DI manager is supposed to be setting it correctly anyway

**Comment by hammol04** [comment]
Can't see the harm in this, safe addition 👍  Did you run into a particular issue which caused you to do this PR @djmarland

**Comment by djmarland** [comment]
Yes. When generating feeds (so not using `script/server`) this causes errors

**Pull request merged**
